[package]
name = "wasm-core"
version = "0.1.0"
authors = ["losfair <zhy20000919@hotmail.com>"]
description = "Portable WebAssembly implementation"
license = "LGPL-3.0"
keywords = ["wasm", "webassembly"]

[dependencies]
serde = { version = "1", default-features = false }
serde_derive = { version = "1", default-features = false }
bincode = { git = "https://github.com/losfair/bincode" }
