[package]
name = "translator"
version = "0.1.0"
authors = ["losfair <zhy20000919@hotmail.com>"]

[dependencies]
wasm-core = { path = ".." }
parity-wasm = "0.27.2"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
